### ISSUE TITLE
An event with custom properties contains irrelevant information 

### ISSUE THREAD

**Issue by AshrafTawfeeq** [Appboy/appboy-ios-sdk#182]
# Report
We are sending a lot events with custom properties inside our iOS client. While inspecting the network calls being made, we have found a couple of issues with one particular event that should be sent every time the app is launched.

 *  In new installs, the event is not being sent for the first session but works fine with the rest. 
 * The event contains unrelated info in its body

![Screenshot 2019-03-22 at 11 58 47](https://user-images.githubusercontent.com/8795081/54820136-700db100-4c9e-11e9-92f0-73ad115e377d.png)

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | Any
 SDK Version             |  3.13.0
 Integration Method      | Cocoapods
 Xcode Version           |  Xcode 10.1
 Repro rate              |  all the time (100%) / sometimes x% / only once

**Comment by Bucimis** [comment]
Hi @AshrafTawfeeq 

1) This could be due to normal variation in time between periodic flushes the SDK makes to push data to the Braze servers. If you need an event to make it to Braze immediately after being logged, feel free to call `Appboy.flushDataAndProcessRequestQueue` to force a data flush (see https://appboy.github.io/appboy-ios-sdk/docs/interface_appboy.html#a746fa87363a1530ba655498b4c36a0dd)
2) These are normal/expected braze internal events and are expected behavior - you can safely ignore them.
