### ISSUE TITLE
SDK requires old version of Facebook SDK

### ISSUE THREAD

**Issue by koppacetic** [Appboy/appboy-ios-sdk#23]
The pod spec needs to be updated to require a more current version of the Facebook SDK. It's requiring 3.16.1 which does not support Facebook's Graph 2.0 API.  Facebook is requiring all apps to move to Graph 2.0 by April 30th.

**Comment by Wenzhi** [comment]
Hi,

Due to the evolving landscape of Facebook requirements and integration limitations, our next release will remove our library's dependence on the Facebook SDK and instead expose an interface to pass FB data from your application to Appboy. We plan to have this release out in the next week; we'll close this issue when it's live.

Thank you for informing us about the Facebook SDK update.

**Comment by Wenzhi** [comment]
Hi,

We pushed out release version 2.10.1 on Monday, which removes all dependencies on the Facebook SDK and adds a new interface called ABKFacebookUser in ABKUser. You should now pass Facebook user information to ABKFacebookUser.

Please let us know if you have any other questions.
