### ISSUE TITLE
ABKIDFADelegate.h file not found

### ISSUE THREAD

**Issue by geyuqiu** [Appboy/appboy-ios-sdk#267]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios only
 Platform Version        |  any simulator / iphones
 SDK Version             |  "cordova-plugin-appboy": "git+https://github.com/appboy/appboy-cordova-sdk.git#master",
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.3
 Repro rate              | all the time (100%) 

pod 1.10.0
ionic  6.12.3
cordova 10.0.0

 
## What did you do?
npm run ios:dev

start xcode locally and run it on simulator / device

## What did you expect to happen?

run successfully

## What happened instead?

https://stackoverflow.com/questions/59712247/header-file-missing-error-with-ionic-build-command-only

**Comment by tbelote** [comment]
Here is a sample ionic app that works for me, can you provide a sample that is broken?
https://github.com/tbelote/myApp

**Comment by hokstuff** [comment]
Hi @geyuqiu,

It looks like this issue is similar to [one in our Cordova SDK](https://github.com/Appboy/appboy-cordova-sdk/issues/52) since some of those clients were also using `ionic`. Can you update to the [Cordova SDK version 3.21.0](https://github.com/Appboy/appboy-cordova-sdk/releases/tag/2.21.0) and see if that fixes your issue? If not, feel free to create a new issue in our Cordova SDK's Github repo - thanks!
