### ISSUE TITLE
iframe is always fullscreen

### ISSUE THREAD

**Issue by sclown** [Appboy/appboy-ios-sdk#269]
* [X ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.5.1
 SDK Version             | 3.29.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.1
 Repro rate              | all the time (100%)
 
## What did you do?

Receive custom message with iframe inside

## What did you expect to happen?

The same page as I can see it simple WebView. iframe should be handled by WebView without additional actions.

## What happened instead?

Braze navigates to the url of iframe

## Steps to reproduce

Send custom message with iframe to any other site. Open it on iOS

## Code Snippet

https://github.com/Appboy/appboy-ios-sdk/blob/d8ba6ecc1dda804b9667f48afbbc2abb87676747/AppboyUI/ABKInAppMessage/ViewControllers/ABKInAppMessageHTMLBaseViewController.m#L158

This method is called for iframe load. It interprets this event as click goes to the url of iFrame.
Android SDK doesn't have this behaviour

**Comment by hokstuff** [comment]
Hi @sclown,

[In our iOS documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/overview/#expected-behaviors-by-message-types), we note that our Custom HTML IAMs do not fully support using `iframe`s because of undefined behavior. Can you reach out to support@braze.com with more context around this issue (e.g. a campaign link, screenshots / screen recording of what you're seeing, etc)? We will then note it as a feature request and prioritize accordingly.

Thanks!

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity. Please contact us through our Support channels with additional info (see post above) if you have further concerns - thank you!
