### ISSUE TITLE
iOS9 Bitcode

### ISSUE THREAD

**Issue by dustfire** [Appboy/appboy-ios-sdk#29]
When I try to compile in XCode7 with Swift2 and your latest Pod -- here is the error:

Appboy-iOS-SDK/AppboyKit/libAppboyKitLibrary.a(ABKItunesStoreProduct.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor,

Any ideas?

**Comment by Wenzhi** [comment]
Hi @dustfire ,

It's because in the new Xcode 7, the "Enable Bitcode" in the build settings is automatically set to YES, and that requires all the third party libraries you use to use bitcode.

This can be fixed by:
(1) Go to your project's build settings, and set the "Enable Bitcode" to be NO.
(2) Wait for our new SDK for iOS 9. The new SDK is currently under development and will be released after the iOS 9 stable version comes out.

Let me know if you have more questions.
