### ISSUE TITLE
SDK 4.0.2 integration breaks rome upload

### ISSUE THREAD

**Issue by rak-sascha** [Appboy/appboy-ios-sdk#290]
We've updated to Braze SDK 4.0.2 and the new method of how the SDk is integrated via Carthage seems to break our CI from uploading the pre-built rome dependency which is supposed to be downloaded locally.

`binary “https://raw.githubusercontent.com/Appboy/appboy-ios-sdk/master/appboy_ios_sdk_full.json”`

Any advice from Braze support about this?

**Comment by lowip** [comment]
Hi @rak-sascha,

Thanks for filing this issue. We do not have experience with Rome and any additional details you can provide us would be extremely helpful (minimum reproducible case, stack traces, logs, etc.)

What package manager / Braze SDK version were you using before the update? Was the CI setup similar?

**Comment by rak-sascha** [comment]
Hi lowip! We've used Carthage and Braze SDK v3.21.3 before the update. We're using Rome (https://github.com/tmspzz/Rome) to provide pre-buillt Carthage dependencies from our CI side. It looks like the different integration of Braze as a binary breaks the integration when using Rome. Sorry, I cannot provide log data or traces since this is a commercial project.

**Comment by hokstuff** [comment]
Hi @rak-sascha,

Are you still experiencing issues? If so, it may be easier to discuss your particular setup by contacting support@braze.com, since our current setup does support Carthage but Rome looks like an additional tool on top of that. In your inquiry, it would be helpful to answer some of the questions:
- Were you using Rome when you had the Braze SDK successfully integrated before?
- Does Rome work with other dependencies that use pre-built binaries in a similar format to ours?
- Can you attach any relevant logs, stack traces, or minimum reproducible cases (obfuscated for any sensitive data)?

Thanks!

**Comment by hokstuff** [comment]
I'm closing this thread due to inactivity. If you are still experiencing issues, please contact us through the regular Support channels with the information noted above. Thanks!
