### ISSUE TITLE
setInAppMessagingRegistrationBlocklist on iOS

### ISSUE THREAD

**Issue by ahmetws** [Appboy/appboy-ios-sdk#303]
* [X] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

I'm trying to prevent In app messages on login screen on iOS. I saw Android can block some activities with `setInAppMessagingRegistrationBlocklist`. Is there a function for the same behaviour on iOS?

**Comment by Bucimis** [comment]
Hi @ahmetws, that exact functionality is not available on iOS, since on iOS there isn't an equivalent concept of registering activities (or on iOS's case, view controllers) with the SDK for IAM display. To selectively block IAMs, I would recommend using the IAM delegate, see https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/customization/#in-app-message-delegate and https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/customization/#custom-handling-in-app-message-display

**Comment by hokstuff** [comment]
Closing out this issue due to inactivity. Feel free to contact support@braze.com if the response above did not sufficiently answer your question - thanks!
