### ISSUE TITLE
WatchOS Push notifications?

### ISSUE THREAD

**Issue by dannyhertz** [Appboy/appboy-ios-sdk#305]
Hello! I was hoping to use Braze SDK to send pushes directly to a watch app, but I'm a bit confused how I can even register push tokens directly from the watch when the SDK does not support watchOS? Also assuming I am able to get a watch specific token into Braze, how would I differentiate them from tokens from the iOS app?

* [ x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

**Comment by hokstuff** [comment]
Hi @dannyhertz,

Sorry to keep this request hanging here, as we continued the conversation directly via the Braze support channels. Our SDK supports running on WatchOS using an iOS companion app, and we discussed possible workarounds that may work to differentiate the two tokens from the Apple Watch vs iOS app.

For those following, feel free to comment here with more information or reach out directly at support@braze.com. I'm closing out this issue since the original questions were handled on a separate channel. Thanks!
