### ISSUE TITLE
Push stories. Deeplink for individual pages not working

### ISSUE THREAD

**Issue by rameez-wed** [Appboy/appboy-ios-sdk#306]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name         | iOS
 Platform Version       | 14.6
 SDK Version             |  3.29.0
 Integration Method      |  Carthage
 Xcode Version           |  Xcode 12.4
 Computer Processor      |  Intel-based
 Repro rate              | All the time (100%) 
 
## What did you do?
Implemented Push stories the step by step following the integration guide

## What did you expect to happen?
In the braze dashboard there is interface to provide deeplink to the story. Then there is individual deeplinks for each pages.
When I click on the image for a particular page the deeplink for the page isn't used instead the deeplink for the entire story is used irrespective of the page you click on.

## What happened instead?
![Screenshot 2021-07-06 at 6 53 32 PM](https://user-images.githubusercontent.com/51288612/124608665-86020880-de8c-11eb-90f6-ae79ad423930.png)
Please refer to the screenshot. `Deep link into Application` used even when we tap on a page.

## Steps to reproduce

- Add `github "Appboy/Appboy-iOS-SDK" == 3.29.0` to the Cartfile file.
- Add `[Appboy startWithApiKey:inApplication:withLaunchOptions:];` method in `application:didFinishLaunchingWithOptions:` method in `AppDelegate.m`.
- Run the app.
- Push a story with different deep links to the project. The Deep link into Application URL used every time

## Code Snippet
Exactly done as mentioned in the documentation.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
No customizations.

## Project that demonstrates the issue
Can't put in the app here but will try to create a small app if possible

**Comment by hokstuff** [comment]
Hi @rameez-wed,

Are you able to consistently repro this even if you try our latest SDK version? We have made a few updates since the `3.29.0` version that may help with this issue.

If not, can you contact support@braze.com with more information about your Push Story setup and any customizations you may have around it?

Thank you!

**Comment by rameez-wed** [comment]
Hey @hokstuff yes I'm consistently able to repro even after upgrading to the latest version (4.3.0).

**Comment by esuvf** [comment]
same problem

**Comment by hendych** [comment]
same here

**Comment by lowip** [comment]
Hi @rameez-wed, @esuvf and @hendych,

In order to work around a limitation with notification content extensions we start a 5 second timer starting at the time the push story is clicked (before 3.31.2, the duration of this timer was 1 second). This gives your app 5 seconds to initialize and process the push notification. Past those 5 seconds, the push story _page click_ is handled as a regular push _body click_.

Can you confirm that your applications are able to start in less than 5 seconds or that you didn't stop on a breakpoint during initialization?

Thanks.

**Comment by hokstuff** [comment]
Hi @rameez-wed, @esuvf and @hendych,

Thanks for your patience on this issue! We have released our Swift SDK which has rebuilt some of the logic around Push Stories. You can access [the initial release in early access here](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.0.0) and can stay tuned for future updates with more features coming soon! Let us know if you continue to experience this issue with the new SDK - thank you!
