### ISSUE TITLE
-[ABKPersistentData synchronizeDataToUserDefaults:] KVO crash

### ISSUE THREAD

**Issue by mbanasiewicz** [Appboy/appboy-ios-sdk#330]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report
We are using SDK version 4.4.1 

<img width="1374" alt="Screenshot 2022-01-17 at 10 04 43" src="https://user-images.githubusercontent.com/1093407/149740265-63d071c5-9dc5-497b-b43d-9db707565238.png">

The crash is gaining momentum for us, is Braze dev team aware of this?

**Comment by Bucimis** [comment]
@mbanasiewicz thanks for filing and apologies for the issue. Does "gaining momentum" refer to increased incidence of the bug in production? If so, were those tied to a particular update or integration change you made? Could you also give us a sense of the scale of the numbers?

**Comment by mbanasiewicz** [comment]
@Bucimis Hi, thank you for your reply. 
> Does "gaining momentum" refer to increased incidence of the bug in production?

Yes

> If so, were those tied to a particular update or integration change you made?

Not really, the oldest reports of this crash were reported in December

> Could you also give us a sense of the scale of the numbers?

I'd say we've had around 300 crashes so far but as I've mentioned it's gaining momentum

<img width="287" alt="Screenshot 2022-01-19 at 08 35 08" src="https://user-images.githubusercontent.com/1093407/150085568-a32603e8-b8b8-474f-b4ab-a4e610c74104.png">

**Comment by mbanasiewicz** [comment]
I see that it was reported here as well https://github.com/Appboy/appboy-ios-sdk/issues/240

**Comment by hokstuff** [comment]
Hi @mbanasiewicz,

Thanks for filing this issue and providing context. Since this appears to have the same root cause as the issue you linked above, I will close out this particular one and link it to #240.

We are actually planning to address this issue holistically in our upcoming Swift SDK since it is not a straightforward issue. Please reference [this thread to sign up for our early access program](https://github.com/Appboy/appboy-ios-sdk/issues/325 ) to be updated for when it is ready. Thank you for your patience!
