### ISSUE TITLE
[Feature]: methods for handling `brazeAction` uri's

### ISSUE THREAD

**Issue by psimk** [Appboy/appboy-ios-sdk#355]
### What problem are you facing?

We have a custom UI for in-app messages, and thus have implemented all tracking & logging using the exposed methods. One thing that we haven't found functionality for, are the "custom event" and "custom attribute" on-click behavior for in-app messages and content cards, as is provided by [your dashboard](https://www.braze.com/docs/user_guide/message_building_by_channel/in-app_messages/create#button-actions). 

The Web SDK provides this in the form of [handleBrazeAction](https://js.appboycdn.com/web-sdk/latest/doc/modules/braze.html#handlebrazeaction), but we cannot find an equivalent in the iOS documentation.

### Workarounds

We are thinking about using the key-value pair feature of in-app customisation to specify the "custom event"/"custom attribute" to log out on click, but that involves substantial changes on our part.

**Comment by hokstuff** [comment]
Hi @psimk,

As noted in the documentation linked, the Braze Actions feature is added as of version 5.4.0 of the [Braze Swift SDK](https://github.com/braze-inc/braze-swift-sdk/). In order to take advantage of that new feature on the iOS side, [reference these docs to migrate](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide/) from the Appboy SDK (ObjC) to the Braze SDK (Swift). The on-click behavior would then be triggered automatically without any further code integration on your end.

To manually implement the behavior mentioned in your custom UI when using the Appboy SDK, you can implement [`ABKInAppMessageUIDelegate` as described here](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/customization/setting_delegates/#in-app-message-delegate). Then, you can use the [`onInAppMessageClicked` function](https://github.com/Appboy/appboy-ios-sdk/blob/d6dc3fab432309e1dbb8445bd37d2714a2ce5dd5/AppboyUI/ABKInAppMessage/ABKInAppMessageUIDelegate.h#L90) to log a custom event or a custom attribute, as shown in this [example code](https://github.com/Appboy/appboy-ios-sdk/blob/fed071000722673754da288cace15c1ff8aca432/Example/Stopwatch/Sources/ViewControllers/IAM/Controls/InAppMessageTestViewController.m#L133).

Thanks!
