### ISSUE TITLE
[Bug]: Push notification received after `Appboy.disableSDK`

### ISSUE THREAD

**Issue by remarcus** [Appboy/appboy-ios-sdk#356]
### Platform

iOS

### Platform Version

16.3

### Braze SDK Version

4.5.0

### Xcode Version

14.1

### Integration Method

Swift Package Manager

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. User logs in
  2. Execute `Appboy.start`.
  3.  Execute `Appboy.registerDeviceToken`
  4. User logs out
  5. Execute `Appboy.disableSDK`, `Appboy.requestEnableSDKOnNextAppRun`

### Expected Behavior

User does not receive Push Notifications

### Actual Incorrect Behavior

User receives Push Notifications

### Additional Information

Hey, we face this problem upon user log out. Is there any additional steps that we should execute in the given scenario? Thanks!

**Comment by hokstuff** [comment]
Hi @remarcus,

A user "logging out" is not a concept with the Braze SDK and is something that only happens in the host app. Can you contact support@braze.com with additional context around your integration, since depending on your integration and specific steps to repro, this behavior might be something controlled by Apple / APNs:
- Can you attach verbose logging when you repro this behavior?
- Are you displaying the push notifications on the foreground or background?
- Can you attach your push integration code?

Thanks!

**Comment by remarcus** [comment]
Hi @hokstuff,

Thanks for explaining that Braze does not have such a concept as logging out.

I wanted to understand if SDK supports some way of removing push token for the specified user, because I could not find any information in the documentation. If that's not the case, I will close the issue and just use `unregisterForRemoteNotifications` for the APNs.

Thanks

**Comment by hokstuff** [comment]
Hi @remarcus,

We currently don't support removing a push token for a specific user. Your use case makes sense so you can submit a product request to Support to get this prioritized in our backlog to update our APIs on the iOS SDK.

The workaround with `unregisterForRemoteNotifications` should work, except [Apple's docs](https://developer.apple.com/documentation/uikit/uiapplication/1623093-unregisterforremotenotifications) warns around specific usage of that API. Note that the push token will still be stored in the Braze dashboard even after calling Apple's API, but the notification would not be delivered to the device because it has been unregistered with APNs.

**Comment by remarcus** [comment]
Thanks @hokstuff,

Yes, that's why I wanted to know more how it works. We will talk in our team and will decide on further actions.

Closing the issue,
Thanks!
