### ISSUE TITLE
[Feature]: Upgrade SDWebImage to latest

### ISSUE THREAD

**Issue by aliraza-noon** [Appboy/appboy-ios-sdk#363]
### What problem are you facing?

SDWebImage has problem with gifs on ProMotion display

### Workarounds

I am not aware of a workaround, there is solution available though for this

### Ideal Solution

Use the latest version of SDWebImage

### Other Information

https://github.com/SDWebImage/SDWebImage/issues/3279

https://github.com/SDWebImage/SDWebImage/pull/3280

**Comment by aliraza-noon** [comment]
I labeled this as feature request, this in fact is bug which causing some trouble for our users on new apple devices.

**Comment by jerielng** [comment]
Hey @aliraza-noon, thanks for raising this issue and a corresponding pull request. Since you have forked the repository from your end, is it possible to use the forked version in your app as a workaround?

Our Objective-C Appboy iOS SDK is deprecated, and we recommend upgrading to our [Swift SDK](https://github.com/braze-inc/braze-swift-sdk), which allows you to use Braze independently of an implicit dependency on `SDWebImage`. We also have a [migration guide](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide/) to ease this process.

**Comment by jerielng** [comment]
Hi @aliraza-noon, are you using CocoaPods or SPM to integrate AppboyKit? In either case, the version dependencies for SDWebImage shouldn't limit you from upgrading to the latest version in your app.

For instance, in CocoaPods, we are using the syntax `>= 5.8.2` in our podspec, you should be able to use any version greater than or equal to that by running `pod update SDWebImage` to get the latest version (5.16.0) in your project.

Likewise, for SPM integrations, you can right-click on SDWebImage under your Package Dependencies and then `Update Package`.

**Comment by hokstuff** [comment]
Closing out this issue based on the solution described above. Since the syntax for the podspec and the Package.swift describe the version _floor_, you are able to still update to the latest version of SDWebImage with today's Appboy iOS SDK code.

Thanks!
