### ISSUE TITLE
onInAppMessageReceived() deprecated, no alternative

### ISSUE THREAD

**Issue by shanev** [Appboy/appboy-ios-sdk#57]
Looks like func `onInAppMessageReceived(inAppMessage: ABKInAppMessage!) -> Bool` is deprecated in the latest release, but no alternative is suggested.

Is there another way to test if an in-app message was received?

**Comment by briancaw** [comment]
Hey @shanev,

We deprecated that because with our new triggered in-app messages the old functionary doesn't really make sense.  With triggered in-app messages we periodically sync a configuration with the server, so many IAMs come into the application at once, and it doesn't correlate to their display time.

The old delegate will work as long as we support old-style IAMs, but only for old-style IAMs.  For triggered IAMs, the main benefit/use-case of that delegate - storing the IAM to show at a later time - can be solved by just associating a trigger with the IAM.  

In the triggered-IAM world, the beforeInAppMessageDisplayed delegate (http://appboy.github.io/appboy-ios-sdk/docs/protocol_a_b_k_in_app_message_controller_delegate-p.html#a0ecc07636c52e82648f45d772a9a361b) can be used to intercept the IAM in a way similar to how onInAppMessageReceived used to operate.

Please let us know if that is sufficient for your use case, and if not, it would be great to hear why and if you have any specific recommendations.

Thanks,
Brian
