### ISSUE TITLE
index 0 beyond bounds for empty array [__NSArrayM objectAtIndex:]

### ISSUE THREAD

**Issue by PerrchicK** [Appboy/appboy-ios-sdk#67]
_Version: 2.19.2_
_iPhone 4s, iOS 9.3.1_
The host app crashed due to a call inside `[ABKService requestFinished] (ABKService.m line 61)`
called inside `[ABKService connection:didFailWithError] (ABKService.m line 320)`

Unfortunately I can't provide more details because it's seems to be an internal bug, that was built into the **libAppboyKitLibrary.a** file.

**Comment by Wenzhi** [comment]
Hi @PerrchicK,

We added guarding against this issue in SDK version 2.20.0 (so an upgrade should fix things for you).  However, we are still investigating the root cause of this issue, so if you have reliable steps to reproduce that would be greatly appreciated.

Please let us know if you have any further comments/questions.

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
@PerrchicK Please feel free to reopen the issue if the crash still happens in SDK version 2.20.0 :)

**Comment by PerrchicK** [comment]
Awesome @Wenzhi, thanks :)
