### ISSUE TITLE
Not actually Carthage compatible

### ISSUE THREAD

**Issue by kballard** [Appboy/appboy-ios-sdk#85]
Your README has a "Carthage compatible" badge, but it's not. You're providing a prebuilt framework download that works with Carthage, but if I run Carthage with the `--no-use-binaries` flag (which disables the use of prebuilt frameworks), this repo cannot be built by Carthage. And the reason it can't be built is because this repo doesn't provide a project file that can be used to build it.

**Comment by briancaw** [comment]
HI @kballard 

Thanks for reporting this. 

Can you let us know what command this is failing for? If it's `build`, `checkout`, or `update`, could you instead specify the names of the libraries you want to build from source (space separated)?  i.e. Those commands allow space separated lists of dependencies to apply the action to.

Thanks,
Brian

**Comment by kballard** [comment]
@briancaw Specifying the dependency name isn't going to change anything. This repo simply is not Carthage-compatible. You don't have a project file. There's no possible way you can be Carthage-compatible if you don't have a project file (and shared schemes within that project). The specific error Carthage gives is

> *** Skipped building appboy-ios-sdk due to the error:
> Dependency "appboy-ios-sdk" has no shared framework schemes for any of the platforms: watchOS, iOS

If you want to reproduce this yourself, you need to pass the `--no-use-binaries` flag to Carthage, or you can checkout this repo and run `carthage build --no-skip-current --platform iOS` from within the repo to get the same error.

**Comment by briancaw** [comment]
Hi @kballard,

I'm wondering if you're able to do, for example:

```
carthage update "dep1" "dep2" --no user binaries
carthage update "Appboy-iOS-SDK"
```

such that you don't apply that flag to the update of our library.  

If that's not feasible for you it would be great to know what's blocking things so we can strategize the if/what/when of an update.  Apologies for the confusion on Carthage compatibility - the documentation [on their github](https://github.com/Carthage/Carthage) doesn't make entirely clear that our support wouldn't be considered actual support (and indeed several other folks have used our library with Carthage successfully).

Thanks,
Brian

**Comment by kballard** [comment]
`update` is the wrong command for building, that would be either `bootstrap` (which does fetch, checkout, and build) or `build`. In any case, while it is possible to specify all of the dependencies manually like that, that makes it significantly harder to actually work with Carthage because we can no longer just say `carthage bootstrap`. And it *still* doesn't make this repo qualify as Carthage-compatible.

And besides, we actually want to build Appboy from source. Right now we're getting

> ld: warning: Some object files have incompatible Objective-C category definitions. Some category metadata may be lost. All files containing Objective-C categories should be built using the same compiler.

and at this point I've tested with building everything else from source except for Appboy. The only way to fix this warning is to build all dependencies (that have Obj-C categories) with the same version of the compiler that's used to build the app.

> the documentation on their github doesn't make entirely clear that our support wouldn't be considered actual support

Yes it does. The documentation [states you need shared Xcode schemes](https://github.com/Carthage/Carthage#share-your-xcode-schemes), and also describes how to test with `carthage build --no-skip-current`. This repo doesn't have shared Xcode schemes, because it doesn't have an Xcode project at all, and it fails the `carthage build --no-skip-current` test.

**Comment by kballard** [comment]
Hmm, I just noticed this repo has a file libAppboyKitLibrary.a, which presumably means that building from source won't help anyway >_<

**Comment by briancaw** [comment]
Hi again @kballard,

Indeed we don't publish source at this time so you won't be able to build from source.  Our roadmap does include open-sourcing elements of our SDK (notably our UI - see https://github.com/Appboy/appboy-ios-sdk/issues/44), but we do not have plans to open source the entirety of our SDK in the very near future.  I apologize for the inconvenience.

Regarding advertising Carthage compatibility - I've updated our README to broadcast the specifics of our support (i.e. that we support via prebuilt framework).

Please let me know if you have any other comments/questions/concerns, and thanks again for reporting this.

Brian

**Comment by kballard** [comment]
@briancaw 

Thank you for updating the README to be more accurate. An even better fix would be to add an xcodeproj to this repo that is set up with a shared scheme that produces the expected framework. Even though it wouldn't actually be building from source but would be using the prebuilt static library, this would allow Carthage users to be able to use Appboy when they specify `--no-use-binaries`, which a number of projects do (especially now with the transition to Xcode 8 and Swift 3, where a lot of prebuilt binaries aren't usable).

**Comment by briancaw** [comment]
Hi @kballard 

Thanks for that recommendation - we had considered that when initially doing Carthage support but avoided it because 1) it wasn't clear the prebuilt framework option was as limiting as you describe and 2) it introduces a bit of a maintenance burden on our end.  That said, we always aim to have our SDK be as useable as possible and we're happy to reconsider that solution.

We can't commit to a timeline right now, but I'll update this ticket when we've decided next steps.  

Thanks,
Brian

**Comment by dmiluski** [comment]
Came here to second this ^ Not Carthage compatible. 

Sadly, I reported it would be an easy install to my product team after reviewing the AppBoy page, and was surprised when I found out not Carthage compatible. I'm embarrassed I mentioned that before attempting integration.

As a team (Venmo), we include Carthage dependencies via:
carthage update --no-build --use-ssh --use-submodules

Which pulled in this project, but with the lack of project/framework to drop in.. not sure about next steps, as we have stopped including cocoa pod dependencies.

I'm not sure what you're worried about open sourcing your client code if it requires your platform to function? Linking to the Carthage dependencies you mention comes free by including your own cart file.

**Comment by nickrobin** [comment]
Hi @dmiluski  

Thank you for reaching out. In order to address your specific concerns I will reach out to you directly to discuss further offline as to not flood the comments here. Please keep an eye out for an email to follow!

**Comment by jeffctown** [comment]
@nickrobin same issue for CNN.  You should remove that you support carthage if you really don't.

**Comment by Wenzhi** [comment]
Hey @jeffctown,

Apologies for the incompatibilities that you’re experiencing. Our Carthage support is currently limited to providing our SDK as a prebuilt framework, something we actively call out in our README. We’re actively working to reconsider our approach, and we deeply appreciate all the public feedback.

In addition to this, our Customer Success and Support teams will be reaching out to you directly to enable a more in-depth conversation around your current build system and dependency requirements. Thanks for your engagement here—our team depends on these sorts of interfaces to build a great client-facing product!

Best,
Wenzhi

**Comment by marcvanolmen** [comment]
hey,

have you seen how Crashlytics and Carthage is done, they provide framework (static one in their case) and take advantage of the binary specifier in the Cartfile

Then the other 3rd party dependencies needed to be added. 

For example:

```
binary "https://raw.githubusercontent.com/Appboy/Specs/master/Carthage/Appboy-iOS.json"
github "Flipboard/FLAnimatedImage"       
github "rs/SDWebImage"
```

The only work for Appboy is to maintain the spec file ```https://raw.githubusercontent.com/Appboy/Specs/master/Carthage/Appboy-iOS.json```
 that keeps track of the version. 

More details here:


https://github.com/Carthage/Carthage/issues/2036

**Comment by dmiluski** [comment]
Hi Marc,

We don't use binaries. We use submodules, a configuration Carthage supports which makes dependency debugging and partial building super friendly.

B/c Carthage doesn't offer the ability to specify binaries vs submodules per resource, we don't have a way to optionally choose binaries for just your module.

I'm really surprised you feel the need to keep the source code closed since it's just a client and shouldn't have any issues being exposed due to it's only responsibility to relay your info to a web service (which is AppBoy's primary bread and butter).

Dane

**Comment by dmiluski** [comment]
@marcvanolmen I didn't realize there was a "binary" Carthage prefix. I'll experiment with this.

As for FLAnimatedImage and SDWebImage, I believe earlier I ran into an issue as SDWebImage duplicates classes that are in FLAnimatedImage? As part of the AppBoy podspec, the spec actually strips out a couple components of one to get it to function?

**Comment by dmiluski** [comment]
@marcvanolmen any chance this could be drive by GitHub releases? Wondering if the separately managed json endpoint is scalable?

**Comment by dmiluski** [comment]
But this looks potentially doable. @appboyci any chance of supporting this by offering a hosted hosted json file to reference?

**Comment by mnvr** [comment]
We use SDWebImage 4.2 in our project, and thus we cannot use the Appboy-iOS-SDK as it stands. Newer versions of SDWebImage integrate the FLAnimatedImage code (if we use the Carthage version), and thus we end up with duplicate code if we use the FLAnimatedImage bundled with the Appboy SDK.

These are the steps I had to do to integrate it with our project:

- Download the [Appboy-iOS-SDK release](https://github.com/Appboy/appboy-ios-sdk/releases/download/3.3.0/Appboy_iOS_SDK.framework.zip).
- From the zip file, copy only `Appboy_iOS_SDK.framework` and add it to our project.
- At runtime, the Appboy_iOS_SDK.framework goes looking for `@rpath/SDWebImage.framework/SDWebImage` and `@rpath/FLAnimatedImage.framework/FLAnimatedImage`. The former is present in my app bundle (since we use SDWebImage) but the latter is not (since, as I mention, this code now lives in SDWebImage itself). To work around this, I create an empty framework project called `FLAnimatedImage`, build it using `carthage build --platform ios --no-skip-current`, and the embed the resulting `FLAnimatedImage.framework` into the app as part of the `carthage copy-frameworks` step.

Needless to say, this is very hacky.

Please provide a variant of your SDK that works for projects that are using Carthage, and are also using SDWebImage 4.x already in their code. The suggestion by @marcvanolmen (https://github.com/Appboy/appboy-ios-sdk/issues/85#issuecomment-342624369) appears to be a good and easy enough approach to get started on.

**Comment by Nonnus** [comment]
is there any solution about this? we were just bitten by the same issue and are trying to find any way to keep building our app without temporarily removing appboy or sdwebimage

**Comment by Nonnus** [comment]
by the way, until now we were able to avoid this problem by using SDWebImage version 4.1.0 but that versions is having too many issues and we needed to update it so we are now faced with the `FLAnimatedImage` collision

**Comment by artxj** [comment]
Hello,

We have updated the Braze SDK, so now you can include only thin framework plus its dependencies by adding the following lines in your Cartfile:

```
binary "https://raw.githubusercontent.com/Appboy/appboy-ios-sdk/master/appboy_ios_sdk.json"
github "rs/SDWebImage"
github "Flipboard/FLAnimatedImage"
```

Please let us know if it doesn't work for you. Thanks again for pointing this out!

**Comment by mnvr** [comment]
Thank you for progress on this 👍🏼

Unfortunately this still doesn't work for us, because the Appboy SDK directly uses FLAnimatedImage 
instead of using the copy of FLAnimatedImage that comes with SDWebImage (which happens by
default, if one uses Carthage, and AFAIK, is not overridable).

i.e., the Appboy SDK uses

    #import <FLAnimatedImage/FLAnimatedImage.h>

However, if we install SDWebImage via Carthage, then the FLAnimatedImage
that is linked with our code is:

    #import <SDWebImage/FLAnimatedImage.h>

Note that we cannot work around this by adding a direct reference to the FLAnimatedImage
framework in our Cartfile because that leads to duplicate symbols (and the associated
compile/runtime errors).

So for now, we still have to use the workaround outlined in https://github.com/Appboy/appboy-ios-sdk/issues/85#issuecomment-354462781

**Comment by dmiluski** [comment]
I'm generally confused why this package uses both SDWebImage + FLAnimatedImage, given SDWebImage now supports GIFs by adding the GIF decoder included in their code.

**Comment by artxj** [comment]
Hi,

Thank you for letting us know and apologies for the incompatibilities that you’re experiencing!

We believe it's an SDWebImage + Carthage package manager issue that leads to FLAnimatedImage sources to be put inside of SDWebImage framework instead of being added as a dependency (see https://github.com/rs/SDWebImage/issues/2279)

Unfortunately we can't simply change ```#import <FLAnimatedImage/FLAnimatedImage.h>``` in our code with ```#import <SDWebImage/FLAnimatedImage.h>``` because the SDK still requires FLAnimatedImage to be linked, otherwise it won't work via Cocoapods integration. 

Also, duplicate symbols when adding a reference to FLAnimatedImage in the Cartfile shouldn't lead to any compile/runtime errors if you use same FLAnimatedImage versions in SDWebImage and as separate framework.

As soon as SDWebImage replaces FLAnimatedImage with its own implementation https://github.com/rs/SDWebImage/pull/2140, or fixes an issue with FLAnimatedImage dependency, we'll update the SDK to solve this issue.

Best, Artem

**Comment by dmiluski** [comment]
@artxj , what do you use FLAnimatedImage for that SDWebImage UIImage does not offer?

**Comment by artxj** [comment]
We've been using FLAnimatedImage for GIF animation (this issue arose only in SDWebImage v.4 when it started bundling FLAnimatedImage).

We're investigating the option of dropping FLAnimatedImage in favor of using SDWebImage GIF coder - we'll update as we make progress there.

Thank you!
