### ISSUE TITLE
getActionWithIdentifier:forRemoteNotification:completionHandler: and iOS8

### ISSUE THREAD

**Issue by Reflejo** [Appboy/appboy-ios-sdk#95]
By making `getActionWithIdentifier:forRemoteNotification:completionHandler:` ` NS_DEPRECATED_IOS(9_0, 10_0,"..)`

You guys broke iOS 8 support for that method. Was that intentional?

**Comment by keith** [comment]
Related: https://github.com/Appboy/appboy-ios-sdk/issues/89

**Comment by keith** [comment]
@Wenzhi this broke our integration, was this intentional? What is the recommended way of integrating the SDK for apps that still support iOS 8 but are being deployed with the iOS 10 SDK?

**Comment by Wenzhi** [comment]
Hey @Reflejo and @keith,

Sorry for the issue and the late reply! This is not intentional; it's totally a mistake on our end. We have been preparing a release to fix it as soon as we saw this issue. 

The release should be out today in the afternoon. I'll ping you in this issue at the moment we release it.

Apologize again for breaking the integration and all the inconvenience. We will be more careful in the future and won't allow this kind of mistakes happen again.

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
Hey @Reflejo and @keith,

We just released 2.24.4 with the fix. I'm going to keep the issue open until you guys confirm the deprecation warnings work for you.

Sorry again for the issue! Thanks for keep using the latest Appboy SDK and reporting issues so fast, we appreciate it! :)

Thanks,
Wenzhi

**Comment by briancaw** [comment]
Hi @Reflejo @keith 

Assuming this is working and going to close this out for now; please feel free to reopen if you still see this issue.

Thanks,
Brian
