### ISSUE TITLE
ABKInAppMessageControllerDelegate changes ON CLICK BEHAVIOR to ABKInAppMessageDisplayNewsFeed

### ISSUE THREAD

**Issue by MaciejMCh** [Appboy/appboy-ios-sdk#96]
In iOS app, I use ABKInAppMessageControllerDelegate to perform custom InApp displaying. In AppBoy dashboard, ON CLICK BBEHAVIOR of InApp is set to redirect to uri. On iOS app, all methods of ABKInAppMessageControllerDelegate are receiving ABKInAppMessage with ABKInAppMessageClickActionType set to ABKInAppMessageDisplayNewsFeed, and uri set to nil. When opening In App Message without ABKInAppMessageControllerDelegate, it redirects to proper uri.

**Comment by chshapiro** [comment]
Hi @MaciejMCh,

Thanks for reaching out! Do you have buttons in your in-app message? When you're setting the on click behavior in the dashboard to redirect to uri, is that for a button or for the actual message?

When you have buttons in your message, the click action type for the actual message defaults to ABKInAppMessageDisplayNewsFeed but nothing actually happens when the message is clicked.

If you want to access the click action type of a button in the delegate method, you can use the following code:

```
- (ABKInAppMessageDisplayChoice)beforeInAppMessageDisplayed:(ABKInAppMessage *)inAppMessage
withKeyboardIsUp:(BOOL)keyboardIsUp {
   if ([inAppMessage isKindOfClass:[ABKInAppMessageImmersive class]]) {
      ABKInAppMessageImmersive *immersiveIAM = (ABKInAppMessageImmersive *)inAppMessage;
      NSArray<ABKInAppMessageButton *> *buttons = immersiveIAM.buttons;
      for (ABKInAppMessageButton *button in buttons) {
         // You can get the value of each button using button.buttonClickActionType
      }
   }
}
```

Please let us know if this is not your issue or if you have any further questions.

Thanks,
Chava

**Comment by MaciejMCh** [comment]
Hi @chshapiro,
Thanks for quick response. Behavior is set on button and I can see my links in code you attached. I will use it to fix my problem. Thank you and I'm closing issue :)
